services:
  proof-server:
    image: CredShieldntwrk/proof-server:8.0.3
    command: ['CredShield-proof-server', '-v']
    container_name: "proof-server_$TESTCONTAINERS_UID"
    ports:
      - '0:6300'
